### ISSUE TITLE
Color in phpstrom terminal?

### ISSUE THREAD

**Issue by ankitpokhrel** [abhimanyu003/phpstorm-spacegray#6]
Thank you for the great theme. But looks like colors for terminal is missing. This is how terminal looks like in spacegray theme:
![spacegray](https://cloud.githubusercontent.com/assets/2364546/9902242/9a0e916e-5c8c-11e5-97a0-136a901d7916.png)

It would be great if terminal could be displayed in colors like this:
![dracula](https://cloud.githubusercontent.com/assets/2364546/9902247/a672c1fa-5c8c-11e5-9d2d-e63ae2d48bfb.png)

**Comment by abhimanyusharma003** [comment]
Can you create PR ?
